# url of daily bond transactions
# Example: https://tw.stock.yahoo.com/s/list.php?c=%C2d%A4%BD%A5q&rr=0.96324200%201486284133
# Caveat: this program currently only supports the transactions provided by Yahoo website shown in the above example.
urlBondDaily: https://tw.stock.yahoo.com/s/list.php?c=%C2d%A4%BD%A5q&rr=0.96324200%201486284133

# url of published bonds
# Caveat: please check if column order is { 債券代號=0,債券簡稱=1,發行人=2,發行日期=3,到期日期=4,年期=5,發行總面額=6,發行資料=7 }
# deprecated
urlBondPublished: https://www.tpex.org.tw/web/bond/publish/convertible_bond_search/memo_download.php?d=issue.txt

# path of output file in CSV format (https://en.wikipedia.org/wiki/Comma-separated_values)
# Example 1 (Windows): D:\Users\chunpei.cheng\Documents\cb.txt
# Example 2 (Mac, Linux, Unix): /Users/chunpei.cheng/Documents/cb.txt
outputFilePath: ../cb.txt

# processing/transaction fee
# Example: 0.001425
fee: 0.001425

# interest tax
# Example: 0.1
tax: 0.1

# For those who have closing prices higher than the threshold, they will be filtered out.
# Example: 100.00
thresholdClosingPrice: 100.00

# 還本價
returnPrice: 100.00

# url of fixed assets and long-term investments
# Example: http://fund.bot.com.tw/z/zc/zcp/zcpa/zcpa0.djhtm?b=Y&a=4804
urlCash: http://fund.bot.com.tw/z/zc/zcp/zcpa/zcpa0.djhtm?b=Y&a=%s

# url of close price, 每股淨值
# Example: http://fund.bot.com.tw/Z/ZC/ZCA/ZCA_6803.DJHTM
urlProfile: http://fund.bot.com.tw/Z/ZC/ZCA/ZCA_%s.DJHTM

# url of TSE price
# Example: http://www.twse.com.tw/exchangeReport/STOCK_DAY?response=json&date=20180301&stockNo=2912
urlTsePrice: http://www.twse.com.tw/exchangeReport/STOCK_DAY?response=json&date=%s&stockNo=%s

# url of OTC price
# Example: http://www.tpex.org.tw/web/stock/aftertrading/otc_quotes_no1430/stk_wn1430_result.php?l=zh-tw&o=htm&d=107/05/29&se=EW&s=0,asc,0
urlOtcPrice: http://www.tpex.org.tw/web/stock/aftertrading/otc_quotes_no1430/stk_wn1430_result.php?l=zh-tw&o=htm&d=%s&se=EW&s=0,asc,0


